#!/bin/sh
#
# rc.d script for pkg-updated
#
# $Id$

# PROVIDE: pkg-updated
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable pkg-updated:
#
#  pkgupdated_enable (bool):    Set to "NO" by default
#                               Set it to "YES" to enable pkg-updated
#  pkgupdated_user (str):       Useraccount which is running as
#  pkgupdated_flags (str):      Parameters for the command it self
#

. /etc/rc.subr

name=pkgupdated
rcvar=pkgupdated_enable

load_rc_config $name

: ${pkgupdated_enable="NO"}
: ${pkgupdated_user="nobody"}
: ${pkgupdated_flags=""}

command="/usr/local/bin/pkg-updated"
pidfile="/var/run/${name}.pid"

start_cmd="${name}_start"

pkgupdated_start()
{
	local pid
	pid=check_pidfile $pidfile $command

	if [ -n "${pid}" ]; then
		echo "${name} already running (pid=${pid})";
		return 1
	fi
	echo -n "Starting ${name}"
	/usr/sbin/daemon -f -p ${pidfile} -u ${pkgupdated_user} ${command} ${pkgupdated_flags}
	echo " ...done"
}

run_rc_command "$1"
